version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/orientation
    ports:
      - "3000:3000"
    depends_on:
      - db
